### ISSUE TITLE
program order in report

### ISSUE THREAD

**Issue by hainm** [Amber-MD/CMakeConfigScripts#6]
Jamie,

is there any order for below? (got from cmake ../amber)

```
--                              Building Tools: 
 gbnsr6 lib cifparse addles sander nmr_aux nmode antechamber sqm reduce sebomd emil ndiff-2.00 cpptraj pbsa sff rism nab nss etc mdgx xtalutil saxs mm_pbsa paramfit FEW amberlite cphstats nfe-umbrella-slice leap chamber parmed mmpbsa_py pymsmt pysander pytraj
```

**Comment by multiplemonomials** [comment]
They are ordered with dependencies (e.g. sqm) before dependers (e.g. sander).  Other than that, it's arbitrary.  I copied the ordering from `AmberTools/src/Makefile`.  The order is defined by the array `AMBER_TOOLS` in `cmake/WhichTools.cmake`

**Comment by hainm** [comment]
Can we sort when display?

**Comment by multiplemonomials** [comment]
sure, but sort by what?

**Comment by hainm** [comment]
abc

**Comment by multiplemonomials** [comment]
Alphabetically?  Sure, I'll try to do that tonight.
